spring:
  datasource:
    url: jdbc:postgresql://dpg-cr3b9mij1k6c73djhjag-a.singapore-postgres.render.com/ecom_g8ph
    username: neha
    password: pmKkA9OktOXFPA0rnEXg6NOwfBdyqFXu
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
      access-token-expiration: 86400000
      refresh-token-expiration: 604800000
